AllCops:
  NewCops: enable
  Exclude:
    - 'assets/**/*'
    - 'vendor/**/*'
  DisplayCopNames: true
  TargetRubyVersion: '2.5'
  SuggestExtensions: false
MethodLength:
  Max: 50
Style/ClassLength:
  Max: 150
Style/CyclomaticComplexity:
  Max: 20
Metrics/BlockLength:
  Max: 30
Metrics/AbcSize:
  Max: 30
require:
  - rubocop-rake
  - rubocop-minitest
  - rubocop-performance
