# SPDX-FileCopyrightText: Copyright (c) 2016-2026 Yegor Bugayenko
# SPDX-License-Identifier: MIT
---
AllCops:
  NewCops: enable
  Exclude:
    - 'assets/**/*'
    - 'vendor/**/*'
  DisplayCopNames: true
  TargetRubyVersion: '2.5'
  SuggestExtensions: false
Metrics/MethodLength:
  Max: 50
Metrics/ClassLength:
  Max: 150
Metrics/CyclomaticComplexity:
  Max: 20
Metrics/BlockLength:
  Max: 30
Metrics/AbcSize:
  Max: 30
Elegant/NoClassInModule:
  Exclude:
    - 'lib/**/*'
    - '**/test_*.rb'
    - '**/*Test.rb'
Elegant/NoRedundantVariable:
  Exclude:
    - 'test/**/*'
plugins:
  - rubocop-rake
  - rubocop-minitest
  - rubocop-performance
  - rubocop-elegant
