docker:
  image: yegor256/rultor-image:1.22.0
assets:
  rubygems.yml: yegor256/home#assets/rubygems.yml
install: |
  pdd -f /dev/null
  bundle install --no-color
release:
  pre: false
  script: |-
    bundle exec rake clean test rubocop copyright
    sed -i "s/1\.0\.snapshot/${tag}/g" lib/xembly/version.rb
    git add lib/xembly/version.rb
    git commit -m "version set to ${tag}"
    gem build xembly.gemspec
    chmod 0600 ../rubygems.yml
    gem push *.gem --config-file ../rubygems.yml
merge:
  script: |-
    bundle exec rake clean test rubocop copyright
